name: Go

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build
      - name: Run tests
        run: go test -v
